[package]
name = "cookie-auth"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
loony = { git = "https://github.com/sankar-boro/loony" }
loony-identity = { git = "https://github.com/sankar-boro/loony-extras" }
env_logger = "0.8"
