[package]
name = "unix-socket"
version = "1.0.0"
authors = ["Messense Lv <messense@icloud.com>"]
edition = "2018"

[dependencies]
loony = { git = "https://github.com/sankar-boro/loony" }
env_logger = "0.8"
